### ISSUE TITLE
React Issue

### ISSUE THREAD

**Issue by michaelfemi81** [hidglobal/digitalpersona-devices#13]
Uncaught Error: Cannot find module 'WebSdk'
I have gone through all the issues and I have tried to implement everything.
I included Websdk to index.html and still same issues. How hard is it to include one module and everyone keeps getting this issue

**Comment by a-bronx** [comment]
The `WebSdk.js` must be included on a **browser side only**. Make sure it is not included in any server-side rendering part. Most of the issues are caused by developers including the WebSdk.js in a wrong place (SSR), not because it is not a separate module.

**Comment by michaelfemi81** [comment]
Im using the create-react-app template so it is not server rendered, I had to comment out the import websdk from the file in the node modules folder . But now the device is not discovered and all drivers have been - installed

**Comment by a-bronx** [comment]
Add `<script src="path/to/WebSdk/index.js"></script>` [in your HTML page](https://github.com/hidglobal/digitalpersona-sample-angularjs/blob/2c54be9c09434bdac39298162e4e6ff7316038c7/src/index.html#L31). Make sure the browser successfully loads the script into the page.

If you need to [import WebSdk](https://github.com/hidglobal/digitalpersona-sample-angularjs/blob/2c54be9c09434bdac39298162e4e6ff7316038c7/src/index.ts#L11) for types, make sure you have [WebSdk typings](https://github.com/hidglobal/digitalpersona-sample-angularjs/tree/master/src/modules/WebSdk) in the import path. You should not import any library code into your JS/TS, only typings.

**Comment by michaelfemi81** [comment]
I already did all that and the issue im getting now is that, the browser doesn't detect the fingerprint

**Comment by michaelfemi81** [comment]
I get Uncaught (in promise) Error: Communication failure... When I call this function reader.startAcquisition(SampleFormat.Intermediate);

**Comment by a-bronx** [comment]
Do you have DigitalPersona Lite Client installed on the client machine? See [this thread](https://github.com/hidglobal/digitalpersona-sample-angularjs/blob/2c54be9c09434bdac39298162e4e6ff7316038c7/src/index.html#L31).

**Comment by michaelfemi81** [comment]
Yes I installer the device driver and the fingerprint device is blinking, the blinking changes when I run my thumb over it, so im assuming its working

**Comment by a-bronx** [comment]
The Lite Client is not a device driver, it is a user agent providing a local web service and a communication channel between the hardware driver and a browser. Browsers are sandboxed and cannot communicate with devices directly, hence the need of the agent. You should see a `DpAgent.exe` process running in your Task Manager.

See [more details and links in the documentation](https://hidglobal.github.io/digitalpersona-devices/).

**Comment by michaelfemi81** [comment]
I tried installing this software and it is not compatible with my Windows 10 computer. Also is it possible to get the scan in FMD format directly from the javascript so I can compare directly with the data stored in the db

**Comment by a-bronx** [comment]
There should be no Win10 compatibility problems in the Lite Client. Can you share details here? If you have an installation error, can you provide an MSI log ([turn logging on](https://docs.microsoft.com/en-us/troubleshoot/windows-client/application-management/enable-windows-installer-logging) before installing)? If the Lite Client is installed but still cannot connect, check Windows Event Log for errors.

Also, what browser do you use? Note that for MS Edge browser you may need to enable a loopback exemption (e.g. with a PowerShell command `CheckNetIsolation LoopbackExempt -a -n="Microsoft.MicrosoftEdge_8wekyb3d8bbwe"`), because Edge prevents pages to connect to `localhost` by default.

About formats: the library can provide minutia data in a DigitalPersona proprietary format ([`SampleFormat.Intermediate`](https://github.com/hidglobal/digitalpersona-devices/blob/f5d8e49f5da02f12580d859ac2d2248507209e6e/src/devices/fingerprints/sample.ts#L8)) which can be used with DigitalPersona fingerprint matching engine only. If you need compatibility with other matching engines, you need to use your own feature extractor on raw fingerprint images.

**Comment by michaelfemi81** [comment]
Thank you I have figured it out somehow. Also Is the away I can just use the library to match saved data from simpleformat

**Comment by a-bronx** [comment]
This library is for fingerprint acquisition only. To use `SampleFormat.Intermediate` for enrollment and authentication you'll need either the DigitalPersona Authentication Server (if you need a turn-key solution integrated with ActiveDirectory or LDS), or the DigitalPersona SDK (if you want to do your own solution using DigitalPersona fingerprint matching engine). For that please inquire HID DigitalPersona [Professional Services](https://www.hidglobal.com/professional-services) team.

**Comment by michaelfemi81** [comment]
Thanks I will close the issue now, but the library is not useful for me and I just wasted my money on the devices I got as all I need is just to confirm that a user entered an information, and there is no easier way to do this and there is no time to start creating my own feature extraction and matching engine, it will be very nice if we can just compare samples gotten from the library, that will open doors to alot of applications

**Comment by kashanalikhalid** [comment]
hello michael can you tell me how you solved the issue? i am stuck on same thing
Thanks in advance

**Comment by omerts** [comment]
I have no server side rendering and it is still failing with the same error during the build

**Comment by FelipeLozano100** [comment]
Lograron solucionarlo?

**Comment by fayizqureshii** [comment]
Hey @michaelfemi81 , Do you figure this out with react?

**Comment by omarasael1980** [comment]
Could anyone implement it in React? It has only worked for me in Angular, I need to be able to read the fingerprint and extract the base64

**Comment by omarasael1980** [comment]
I finally managed to implement fingerprint scanning in my project, displaying it as an image or base64 in the console. You can find the code on my GitHub: https://github.com/omarasael1980/digitalPersonaReact/. It's a simple fingerprint reading implementation using @digitalpersona/devices in React. Feel free to check it out, and I hope it proves helpful to anyone working on a similar project!
