### ISSUE TITLE
Biometric authenctication into Eletron application

### ISSUE THREAD

**Issue by prakashnarkhede91** [hidglobal/digitalpersona-devices#16]
@a-bronx 
Hi Team,
We are having a biometric finger print authentication into our Elector application, I have achieved the functionality with the help of node-fprint npm, My electron application running on node 12, and npm having max support for node 8. We tried all possible solutions to upgrade the npm but no success, Can you guys please help me with this? Please help us :(

Thanks,
Prakash

**Comment by a-bronx** [comment]
This repository is not related with the `node-fprint` package. You should ask [node-fprint](https://github.com/ephraim/node-fprint/issues) maintainers.
