### ISSUE TITLE
Supported List of Devices.

### ISSUE THREAD

**Issue by rabiulislamanik** [hidglobal/digitalpersona-devices#18]
Can I use any digital persona fingerprint scanner device to integrate with?

If not, it would be great to mention the list of supported devices in the docs.

**Comment by a-bronx** [comment]
The the JavaScript library itself is abstracted from the hardware level. Being a high-level API, it does not interact with devices directly. All interaction with the hardware is provided by the DigitalPersona Workstation or DigitalPersona Lite Client, a native Windows service/application that should be installed on the client computer. You should be able to use any DigitalPersona fingerprint scanner supported by these products. You can check the [DigitalPersona product page](https://www.hidglobal.com/products/software/digitalpersona/digitalpersona) for details.
