### ISSUE TITLE
HID DigitalPersona Lite Client For Android

### ISSUE THREAD

**Issue by kachun333** [hidglobal/digitalpersona-devices#19]
I have built a React app integrated with Digital Personal u are u 4500 using this library. 
It works great on Windows machines.

I am aware that for this library to works, _HID DigitalPersona Lite Client_ is essential, therefore I'm wondering does the _lite client_ is available on Android? I wish to connect to the fingerprint reader via OTG so that our web app can listen to the fingerprint image captured on Android.

Thanks in advanced

**Comment by a-bronx** [comment]
Hello, thank you very much for choosing our library.

Unfortunately, we do not Lite Client versions for any other OS but Windows.
