### ISSUE TITLE
How to know what's the driver this library is interacting with?

### ISSUE THREAD

**Issue by Abdullah0991** [hidglobal/digitalpersona-devices#20]
Hello,

Is there a way to know the name or id of the driver this library is interacting with? i.e: WBF or RTE?

**Comment by Abdullah0991** [comment]
...

**Comment by a-bronx** [comment]
You can use a [`FingerprintReader.getDeviceInfo()`](https://github.com/hidglobal/digitalpersona-devices/blob/master/src/devices/fingerprints/reader.ts#L158) method to obtain a [`DeviceInfo`](https://github.com/hidglobal/digitalpersona-devices/blob/master/src/devices/fingerprints/device.ts#L40) structure containing a device id and other information.
