### ISSUE TITLE
Module not found: Error: Can't resolve 'WebSdk'

### ISSUE THREAD

**Issue by danielcuellarp** [hidglobal/digitalpersona-devices#28]
Hi, 

When I create a variable and an instance of "FingerprintReader", the result is:

./node_modules/@digitalpersona/devices/dist/es6/devices/websdk/channel.js:3:0-16 - Error: Module not found: Error: Can't resolve 'WebSdk' in '...\node_modules\@digitalpersona\devices\dist\es6\devices\websdk'

![image](https://user-images.githubusercontent.com/17932445/179635430-e9d5b652-a547-4e27-b5e4-f4fe05b2e3b8.png)

I already have the index.js file in the script tags as mentioned.

![image](https://user-images.githubusercontent.com/17932445/179635709-81662c4e-73cc-4d47-8cde-bc2b8bf5d6f3.png)

**Comment by a-bronx** [comment]
Hello,

The WebSdk is a browser-only library, and must be loaded only into a browser context -- either as a static resource, or as a part of a bundle. The error message suggests that you try to load the WebSdk from the `node_modules`, which is clearly not expected to be seen in a browser. You must exclude the WedSdk library from a Node module resolution, and the code that depends on it must execute only in a browser as well.
