### ISSUE TITLE
compare two acquisition with sampledata 

### ISSUE THREAD

**Issue by birladotech** [hidglobal/digitalpersona-devices#30]
after having the data in base64 or base64url format with the sampleData. I want to be able to save the data to a database and be able to compare the fingerprint of the people again. I use an api to send the data to my server but I can't compare the users.

**Comment by a-bronx** [comment]
Hello,

To compare fingerprints, you need some fingerprint matching engine, like HID DigitalPersona FingerJet (a part of [HID DigitalPersona Suite](https://www.hidglobal.com/products/software/digitalpersona/digitalpersona)).
