### ISSUE TITLE
HID DigitalPersona Lite Client download link

### ISSUE THREAD

**Issue by tnfuv** [hidglobal/digitalpersona-devices#34]
Hi,

I'm following the tutorial for the past few weeks and was successfully downloaded the HID DigitalPersona Lite Client on my machine. But now when I go to this download [link](https://www.crossmatch.com/AltusFiles/AltusLite/digitalPersonaClient.Setup64.exe) it is not working anymore. Can anyone point me to the right link for this.

**Comment by a-bronx** [comment]
Thank you for the report, we're working with our IT to restore the link.
At this moment the Lite Client is accessible at https://**www3**.crossmatch.com/AltusFiles/AltusLite/digitalPersonaClient.Setup64.exe

**Comment by a-bronx** [comment]
The link is restored.
