### ISSUE TITLE
Communication failure: Digital Persona 4500

### ISSUE THREAD

**Issue by okothhillary** [hidglobal/digitalpersona-devices#37]
I keep getting a communication error when I try to connect DP 4500 to my web app. Below is a test file that reproduces the issue I'm facing. I already have DigitalPersona Lite Client and DIGITALPERSONA 4500 WBF DRIVER installed.

[test.zip](https://github.com/hidglobal/digitalpersona-devices/files/10977205/test.zip)

**Comment by okothhillary** [comment]
That error is displayed on all browsers that I've tried. I've allowed loopback in MS Edge, I've checked if there's any firewall blocking connection but I haven't seen any after posting "https://127.0.0.1:52181/get_connection", I got something like "endpoint...web_sdk". How do I resolve the communication error?

![Screenshot (550)](https://user-images.githubusercontent.com/93287156/225244199-0d204165-2588-47c5-b0ad-361cb70c247d.png)
![Error](https://user-images.githubusercontent.com/93287156/225244514-2ec25978-8d71-4211-a520-487e83d418d9.jpeg)

**Comment by okothhillary** [comment]
All local agents are running...how do I solve the communication error @a-bronx, @daniilr, @adricasti, @pboulvais ?

**Comment by DanielIcc** [comment]
same error here any sugestions?

**Comment by a-bronx** [comment]
Apologies for a long delay, I was prioritized to work on different projects.

Upon a code inspection I can only say, that the `this.reader.channel.webChannel.connect()` call in the `FingerprintSigninControl` constructor is unnecessary, the `FingerprintReader.startAcquisition()` will try to open the channel automatically in a proper way.

Note that the company policy forbids me to run your test sample with untrusted content. Should you wish me to investigate further, please create a minimal GitHub project reproducing the issue (no third-party libraries). Also specify versions of the browsers you tried and the version of the Lite Client installed.
