### ISSUE TITLE
Where Do I find the Digital Persona 4500 SDK documentation

### ISSUE THREAD

**Issue by arnaldostuff** [hidglobal/digitalpersona-devices#41]
I need to use the SDK and I can find the documentation. Does somebody have the documentation or the link to download it?

Also, what is the default format in which Digital persona 4500 saves the fingerprint image? I have tried to convert from base64 to file and I have not been able to see the image in any way

**Comment by a-bronx** [comment]
This repository is for a `digitalpersona-devices` library only, it is not a generic customer support line.

I'd suggest to inquire the supplier who provided you with the SDK, or write to the [HID Global customer support](https://www.hidglobal.com/contact).
