### ISSUE TITLE
Convert SampleFormat Intermediate to PngImg or PngImg to Intermediate

### ISSUE THREAD

**Issue by rangerisrael** [hidglobal/digitalpersona-devices#49]
sir @a-bronx  it's possible to convert PNG Image to Intermediate sample format or Intermediate to Png Image Format?

**Comment by a-bronx** [comment]
"Intermediate -> PNG" is impossible in principle, because all original image information is lost, only a set of fingerprint features is stored.

"PNG -> Intermediate" requires a call to the DigitalPersona Fingerprint Engine. The library does not provide access to the engine, but you can get DigitalPersona SDK which allows this.

**Comment by rangerisrael** [comment]
@a-bronx can you give sample how I convert Png to Intermediate?

**Comment by rangerisrael** [comment]
@a-bronx what is encoded in Intermediate Sample Format it is base64 / Utf8 / base64 url?

**Comment by a-bronx** [comment]
> can you give sample how I convert Png to Intermediate?

Such sample is a part of the DigitalPersona SDK, you need to obtain the SDK first.

> what is encoded in Intermediate Sample Format it is base64 / Utf8 / base64 url?

A fingerprint feature set in a DigitalPersona proprietary format.

**Comment by rangerisrael** [comment]
> > can you give sample how I convert Png to Intermediate?
> 
> Such sample is a part of the DigitalPersona SDK, you need to obtain the SDK first.
> 
> > what is encoded in Intermediate Sample Format it is base64 / Utf8 / base64 url?
> 
> A fingerprint feature set in a DigitalPersona proprietary format.

@a-bronx  yes I already implement the sdk for digital persona at I get fingerprint image accurately

**Comment by rangerisrael** [comment]
![image](https://github.com/hidglobal/digitalpersona-devices/assets/38226544/3995897a-7821-4bbf-9f10-21056aa4803d)

**Comment by a-bronx** [comment]
> I already implement the sdk for digital persona at I get fingerprint image accurately,

I do not understand what do you mean by this? DigitalPersona Fingerprint SDK is a commercial product, which contains a fingerprint engine (a native Windows dynamic library) and distributed by HID Global. If you have purchased the SDK already, then you should have samples of the code with the distributives, as well as contacth of the SDK support team which can help you.

> I just want to know how could convert Png Image to Intermediate

You need to invoke the DigitalPersona Fingerprint Engine functions. You cannot do it in JavaScript., as this is a native API, ant it is out of the scope of the `@digitalpersona/devices` library, so I cannot provide you with samples.
