### ISSUE TITLE
Fingerprint 5100 module drivers for windows

### ISSUE THREAD

**Issue by KitHubek** [hidglobal/digitalpersona-devices#50]
hello, i cant use Fingerprint  5100 module on windows. Using ~~4600~~ 4500 drivers not working. From where i can download drivers for Fingerprint 5100 module

**Comment by a-bronx** [comment]
Hello,

There are no drivers (in a windows sense, with the inf file). 5100 presents itself as web camera device, and it can't be accessed via DigitalPersona Biometric SDK.
