### ISSUE TITLE
onDataReceivedTxt error

### ISSUE THREAD

**Issue by locent217** [hidglobal/digitalpersona-devices#55]
![Screenshot 2024-01-16 161703](https://github.com/hidglobal/digitalpersona-devices/assets/31910014/e71615ba-df64-45e9-828d-2f6c5e866fdc)

I have the following error. It occurs after I re-start the fingerprint acquisition. Can you help me with the possible cause of it?

**Comment by a-bronx** [comment]
The error 0x80070057 is a Windows HRESULT which translates to a message "The parameter is incorrect." This message comes from the "native" part (Lite CLient or fingerprint API or driver) and a possible cause may be an invalid parameter passed into a method like `startAcquisition()` or `stopAcquisition()`

**Comment by locent217** [comment]
@a-bronx What might be my mistake why I am having this warning? I followed the tutorial so far. Thank you in advance

**Comment by a-bronx** [comment]
Can you provide access to your project's repository or to a repository with a minimal sample reproducing the issue?

**Comment by locent217** [comment]
Hello @a-bronx , I managed to fix it by simply using onBeforeUnmount() in vue3. Basically it is an equivalent of delete in the tutorial. thank you!
