### ISSUE TITLE
Uncaught TypeError: Cannot set properties of undefined (setting 'ifvisible')

### ISSUE THREAD

**Issue by locent217** [hidglobal/digitalpersona-devices#56]
Hi! I have this error on the provided index.js from the webSdk sample.

```
Uncaught TypeError: Cannot set properties of undefined (setting 'ifvisible')
    at index.js:4906:29
    at index.js:4908:5
    at index.js:5198:4
    ```

**Comment by OmarAsael** [comment]
I also have the same issue, i'm trying to implement in react, were you able to solve it?

**Comment by Abiey2579** [comment]
Wow, no one solved this problem yet, am screwed

**Comment by a-bronx** [comment]
I was unable to reproduce the problem, and nobody tried to provide a repo with a minimal reproducible sample. Nevertheless, we're working on a new version of WebSdk which we hope will help to avoid some typical mistakes (where trying to use browser-only WebSdk in a NodeJS is the most typical).

**Comment by JerryA1** [comment]
i have this same error

![Captura de pantalla 2024-09-16 144819](https://github.com/user-attachments/assets/1dee8c44-61e3-4f46-9936-262c33d5ff0c)

**Comment by Abiey2579** [comment]
Did you find the solution, yet?

**Comment by JerryA1** [comment]
> Did you find the solution, yet?

Im using [sdk ](https://github.com/a-bronx/digitalpersona-sample-angularjs/blob/master/src/modules/WebSdk/index.js) from repo of @a-bronx, im finished my app but the build failling

**Comment by a-bronx** [comment]
A `@digitalpersona\websdk` package is now available, please try it.

You may also want to try `@digitalpersona\fingerprint` package (supports only fingerprints) and/or `@digitalpersona\card` (supports only cards).

The `@digitalpersona\devices` may be declared obsolete in near future, and everyone will be encouraged to use those smaller and more targeted packages instead.
