### ISSUE TITLE
Is it possible to generate two outputs simultaneously in a fingerprint scanning action?

### ISSUE THREAD

**Issue by heriira** [hidglobal/digitalpersona-devices#60]
Sir @a-bronx , is it possible to generate two outputs when fingerprinting, namely in WSQ format for storage in the database and PNG format for displaying a preview image of the ongoing scan?
If feasible, are there any examples of its implementation?
Thank you

**Comment by a-bronx** [comment]
No, the fingerprint engine does not supports this, so the library does not too.
