### ISSUE TITLE
deseo migrarlo a php with mysql 

### ISSUE THREAD

**Issue by henrypandales** [hidglobal/digitalpersona-devices#7]
saludos me puedes escribir al +57 314 775 4208 
quiero migrarlo a phpcon mysql para control de personal. gracias

**Comment by a-bronx** [comment]
Hello. This library is for browsers only, there is no point to rewrite it in PHP.

**Comment by henrypandales** [comment]
eny example video or in youtube.com abaut install and use??

**Comment by a-bronx** [comment]
There is a [tutorial](https://hidglobal.github.io/digitalpersona-devices/tutorial.html).
